# See https://mmistakes.github.io/minimal-mistakes/docs/configuration for details about the minimal-mistakes theme configuration.
# The default minimal-mistakes config is available at https://github.com/mmistakes/minimal-mistakes/blob/master/_config.yml

# Required! See https://github.com/asciidoctor/jekyll-asciidoc?tab=readme-ov-file#configuration
asciidoc: {}

asciidoctor:
  attributes:
    icons: font
    source-highlighter: rouge

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-author
author:
  avatar: /assets/images/avatar.png
  bio: Senior Software Engineer/Craftsman experienced in Java/Kotlin
  github: PoisonedYouth
  linkedin: https://www.linkedin.com/in/matthias-schenk-7b7586143
  location: Germany, Freiburg
  name: Matthias Schenk

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#giscus-comments
comments:
  giscus:
    category_name: Announcements
    category_id: DIC_kwDOMmeTc84Ch62-
    discussion_term: "og:title"
    reactions_enabled: "1"
    repo_id: R_kgDOMmeTcw
    theme: dark
  provider: giscus

copyright: Matthias Schenk

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#front-matter-defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      classes: wide
      comments: true
      layout: single
      related: true
      share: true
      show_date: true

description: PoisonedYouth TechBlog - Software Engineering, Kotlin & more

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#code-block-copy-button
enable_copy_code_button: true

encoding: utf-8

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-footer
footer:
  links:
    - label: GitHub
      icon: fab fa-fw fa-github
      url: https://github.com/PoisonedYouth
    - label: Linkedin
      icon: fab fa-fw fa-linkedin
      url:

locale: de-de

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#skin
minimal_mistakes_skin: dark

remote_theme: mmistakes/minimal-mistakes@4.26.2

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-repository
repository: PoisonedYouth/PoisonedYouth.github.io

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-search
search: true

show_excerpts: true

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-subtitle
subtitle: Software Engineering, Kotlin & more

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#archive-settings
tag_archive:
  type: liquid
  path: /tags/

# See https://mmistakes.github.io/minimal-mistakes/docs/configuration/#site-title
title: PoisonedYouth TechBlog

url: https://poisonedyouth.github.io
